#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Wofi Powermenu

## Files
CONFIG="$HOME/.config/sway/wofi/config"
STYLE="$HOME/.config/sway/wofi/style.css"

## Wofi Command
wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} \
			--width=300 --height=205 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

uptime=$(uptime -p | sed -e 's/up //g')

## Entries
logout=" logout"
lock=" lock"
reboot=" restart"
shutdown=" shutdown"
suspend=" sleep"

# Ask for confirmation
cdialog () {
	yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

# Variable passed to rofi
open_menu () {
	options="$logout\n$reboot\n$lock\n$shutdown\n$suspend"

	chosen="$(echo -e "$options" | $wofi_command --prompt "UP - $uptime")"
	case $chosen in
		$logout)
			cdialog
			if [[ "$?" == 0 ]]; then
				swaymsg exit
			else
				exit
			fi
			;;
		$lock)
			~/.config/sway/scripts/lockscreen
			;;
		$reboot)
			cdialog
			if [[ "$?" == 0 ]]; then
				systemctl reboot
			else
				exit
			fi
			;;
		$shutdown)
			cdialog
			if [[ "$?" == 0 ]]; then
				systemctl poweroff
			else
				exit
			fi
			;;
		$suspend)
			cdialog
			if [[ "$?" == 0 ]]; then
				mpc -q pause
				pulsemixer --mute
				~/.config/sway/scripts/lockscreen
				systemctl suspend
			else
				exit
			fi
			;;
	esac
}

if [[ ! `pidof wofi` ]]; then
	open_menu
else
	pkill wofi
fi

