#! /bin/sh

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# Launch keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

#workspaces
bspc monitor DP-0 -d '' '' '' '' ''
#bspc monitor DP-0 -d '' '' '' '' '' ''
bspc monitor DP-2 -d '' '' '' '' ''
#bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width         2
bspc config window_gap          10

# Border
bspc config focused_border_color "$GREEN"
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle true

bspc config split_ratio          0.52
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# 1 > terminal
declare -a term=(Alacritty Xfce4-terminal Gnome-terminal)
for i in ${term[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

# 2 > code
declare -a code=(Atom Code Gedit Geany Meld code-oss Xed)
for i in ${code[@]}; do
  bspc rule -a $i desktop='^2' state=tiled follow=on focus=on; done

# 3 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
 bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > grfx
declare -a grfx=(Inkscape Gimp-2.10 Viewnior)
for i in ${grfx[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > settings
bspc rule -a GParted desktop='^5' follow=on focus=on
bspc rule -a Pamac-manager desktop='^5' follow=on focus=on
declare -a settings=(Catfish KeePassXC Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > web
declare -a web=(Google-chrome Microsoft-edge)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > chat
declare -a chat=(firefox firefoxdeveloperedition Thunderbird TelegramDesktop Hexchat)
for i in ${chat[@]}; do
	bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > files
declare -a files=(Thunar Nautilus)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^8' follow=on focus=on; done

# 0 > media
declare -a media=(Audacity Music MPlayer Lxmusic obs spotify Spotify)
for i in ${media[@]}; do
  bspc rule -a $i desktop='^10' follow=on focus=on; done

# special rules
declare -a floating=(Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

# spotify rule
	bspc config external_rules_command "$HOME/.config/bspwm/bin/spotify.sh"


#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Network Applet
nm-applet &

# Fix cursor
xsetroot -cursor_name left_ptr

# Set Compose key
setxkbmap -option compose:rctrl &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Network Applet
nm-applet --indicator &

# start blueberry app for managing bluetooth devices from tray:
blueberry-tray &

# Pamac-stalonetray
pamac-tray &

# Restore wallpaper
bash $HOME/.fehbg
#nitrogen --restore

# Start dropbox
exec dropbox &

# Start spotify
wmctrl -r Spotify -t 9

# Start bspwm scripts
bspcolors
bspbar
bspcomp

# Fix non-parenting windows
wmname LG3D

