#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

sh ~/.screenlayout/monitor.sh &

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#
bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10
#bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$GREEN"
bspc config normal_border_color "$MAGENTA"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
#bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > edit
bspc rule -a Atom desktop='^2' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on


# 3 > file
bspc rule -a Thunar desktop='^7' follow=on focus=on

# 6 > web
bspc rule -a firefoxdeveloperedition desktop='^6' follow=on focus=on
bspc rule -a Google-chrome desktop='^6' follow=on focus=on
bspc rule -a Microsoft-edge-beta desktop='^6' follow=on

# 4 > grfx
declare -a media=(Gimp Gimp-2.10 Inkscape)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 3 > office
declare -a office=(Geany Gucharmap Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 9 > media
declare -a media=(Audacity mpv mplayer lxmusic)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^9' follow=on focus=on; done

# 6 > settings
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Nm-connection-editor state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch keybindings daemon
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

# Enable power management
# xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr &
setxkbmap -option compose:rctrl &
numlockx on &

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &

## Adjust backlight (AMD)
#blight -d amdgpu_bl0 set 15%
