#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#monitor setup
#find out names with arandr or xrandr
bspc monitor DP-2 -d 1 2 3 4 5
#bspc monitor LVDS1 -d 1 2 3 4
bspc monitor DP-4 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

#open applications on specific workspaces
bspc rule -a URxvt desktop='^1'  follow=on
bspc rule -a urxvt desktop='^1'  follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a Meld desktop='^2' follow=on
bspc rule -a Gimp desktop='^4' follow=on
bspc rule -a Inkscape desktop='^4' follow=on
bspc rule -a KeePassXC desktop='^5' follow=on
bspc rule -a firefoxdeveloperedition desktop='^5' follow=on
bspc rule -a Microsoft-edge-beta desktop='^6' follow=on
#bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Transmission-gtk desktop='^7' follow=on
bspc rule -a Thunar desktop='^7' follow=on
#bspc rule -a discord desktop='^9' follow=on
bspc rule -a Spotify desktop='^9' follow=on
bspc rule -a Google-chrome desktop='^10' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#BSPWM coloring
#bspc config focused_border_color	"#5e81ac"
bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color		"#4c566a"
bspc config normal_border_color         "#073642"
#bspc config active_border_color		"#1e1e1e"
bspc config active_border_color         "#073642"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


# Autostart
#
sh $HOME/.config/bspwm/autostart.sh &
# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &
# Bar
#~/.config/polybar/launch.sh &
# Notifications
#/usr/bin/dunst &
# Polkit
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
#nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
#picom -CGb &
# Network Applet
#nm-applet --indicator &

# Cursor
#xsetroot -cursor_name left_ptr &

# Compose Key
#setxkbmap -option compose:rctrl &
