#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
if [[ ! `pidof lxpolkit` ]]; then
	/usr/bin/lxpolkit &
fi

# Set wallpaper
swaybg --output 'DP-1' --mode fill --image ~/.config/hypr/wallpapers/sway-wm-01.png &
swaybg --output 'DP-2' --mode fill --image ~/.config/hypr/wallpapers/sway-wm-02.png &
swaybg --output 'DP-3' --mode fill --image ~/.config/hypr/wallpapers/sway-wm-03.png &
swaybg --output 'DP-4' --mode fill --image ~/.config/hypr/wallpapers/sway-wm-04.png &


# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

# Start mpd
exec mpd &

# Start dropbox
exec dropbox &

# Start blueman
exec blueman-applet &
